server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: edge-service
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
