server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: book-service
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
